version: '3'

services:
  app:
    build: .
    container_name: vue-project
    ports:
      - '8080:8080'
    volumes:
      - ./vue-notion:/app
    stdin_open: true
    tty: true
    command: yarn serve
